module.exports = {
    airFriction: require('./airFriction.js'),
    avalanche: require('./avalanche.js'),
    ballPool: require('./ballPool.js'),
    car: require('./car.js'),
    catapult: require('./catapult.js'),
    circleStack: require('./circleStack.js'),
    collisionFiltering: require('./collisionFiltering.js'),
    compositeManipulation: require('./compositeManipulation.js'),
    compoundStack: require('./compoundStack.js'),
    doublePendulum: require('./doublePendulum.js'),
    friction: require('./friction.js'),
    gravity: require('./gravity.js'),
    mixed: require('./mixed.js'),
    newtonsCradle: require('./newtonsCradle.js'),
    pyramid: require('./pyramid.js'),
    restitution: require('./restitution.js'),
    sensors: require('./sensors.js'),
    softBody: require('./softBody.js'),
    sprites: require('./sprites.js'),
    stack: require('./stack.js'),
    stress: require('./stress.js'),
    stress2: require('./stress2.js'),
    stress3: require('./stress3.js'),
    stress4: require('./stress4.js')
};